## Implementation of autoattention 

In [44]:
import torch
import numpy as np

#Vectores Q, K, V

# Calculamos score ie: [q1k1, q1k2, q1k3, q1k4], Q2..., Q3..., Q4...
# Dividimos cada valor por la raiz de D_k
# Aplicamos softmax sobre cada vector 
# Deberia quedas como recultado una matriz DK * DQ
# Multiplicamos la matriz QK por V y luego sumamos para que quede un vector 

Q = torch.tensor([[0.0, 0.0, 0.0], [1, 1, 1], [0.3, 0.3, 0.3], [0.4, 0.4, 0.4]])
K = torch.tensor([[0.1, 0.1, 0.1], [0.2, 0.2, 0.2], [0.3, 0.3, 0.3], [0.4, 0.4, 0.4]])
V = torch.tensor([[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0], [0.0, 1.0, 1.0]])



QK = torch.matmul(Q, K.t())
QK = QK / np.square(K.shape[1])

weights = torch.softmax(QK, dim = 1)
print(weights)
for weight ,i in enumerate(weights):
    
att = WV.sum(dim=1)
att

tensor([[0.2500, 0.2500, 0.2500, 0.2500],
        [0.2376, 0.2457, 0.2540, 0.2626],
        [0.2463, 0.2487, 0.2512, 0.2538],
        [0.2450, 0.2483, 0.2516, 0.2550]])


tensor([1.2500, 1.2626, 1.2538, 1.2550])

In [ ]:
tensor([[0.2500, 0.5000, 0.5000],
        [0.1508, 0.5744, 0.6457],
        [0.2173, 0.5225, 0.5449],
        [0.2070, 0.5300, 0.5597]])